### ISSUE TITLE
Kanban Set Up

### ISSUE THREAD

**Issue by Fayob** [Fayob/ror_recipe_app#7]
[Github project](https://github.com/users/Fayob/projects/4/views/1)

We are team of two members

**Comment by Ghiftee** [comment]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @Fayob and @AshwinCarvalho999 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ The correct columns are on the board
✔️ Cards for tasks have been created
✔️ Cards have task description
✔️ Tasks have been assigned to team members
However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
- [ ] Kindly add cards for the group tasks and assign them to an individual or the group
- [ ] Student A has a total of 10pts for tasks and student B has a total of 8pts. Kindly ensure that the sum of total points for each student are equal.
- [ ] Kindly add a card for the task in the image below as it is currently missing on your board.
![Screenshot 2023-02-06 at 11 38 02 (2)](https://user-images.githubusercontent.com/64774936/216950516-6d5c8dc9-f304-4c87-a564-8760accc0eb8.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- I suggest you include the name of your team members to the issue description to make it more professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Fayob** [comment]
Hi @Ghiftee, we've assigned all the tasks individually, I can't find any other task in project requirement that should be group work

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Fayob and @AshwinCarvalho999,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
